db:
  image: grafana/tns-db
  command:
    - '-log.level=debug'
  ports:
    - 8000:80

app:
  image: grafana/tns-app
  command:
    - '-log.level=debug'
    - 'http://db'
  links:
    - db
  ports:
    - 8001:80

loadgen:
  image: grafana/tns-loadgen
  command:
    - '-log.level=debug'
    - 'http://app'
  links:
    - app
  ports:
    - 8002:80

prometheus:
  image: prom/prometheus
  command: ["--storage.tsdb.retention.time=168h", "--storage.tsdb.retention.size=80GB", "--config.file=/etc/prometheus/prometheus.yml"]
  ports:
    - "9090:9090"
  volumes:
    - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml

node-exporter:
  image: prom/node-exporter
  privileged: true
  ports:
    - "9100:9100"
  command: ["--collector.textfile", "--collector.textfile.directory", "/textfile"]
  volumes:
    - ./node-exporter:/textfile
